name: hydrous-melts
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - pandas
  - ipywidgets
  - pip
  - pip:
      - voila
      - burnman
      - mpltern
      - itables
      - session-info
      - jovian
      - tqdm
