name: hydrous-melts
channels:
 - conda-forge
dependencies:
 - python-3.6.10
 - pip
 - pip:
   - burnman==0.9.0
   - ipywidgets==7.7.0
   - itables==0.3.0
   - jovian==0.2.29
   - matplotlib==3.3.4
   - mpltern==0.3.1
   - numpy==1.19.5
   - pandas==0.25.1
   - scipy==1.5.4
   - session_info==1.0.0
   - tqdm==4.60.0
   - IPython==7.16.1
   - jupyter_client==7.0.6
   - jupyter_core==4.9.1
   - jupyterlab==3.2.9
   - notebook==6.4.1
   - appmode==0.9.0
