#!/bin/bash
set -e

# Notebook you want to auto-run
NB="hydrous_melt_PVTX.ipynb"

# Run all cells and overwrite the notebook with executed version
jupyter nbconvert --to notebook --execute --inplace "$NB"

# Hand over to the normal Jupyter entrypoint
exec "$@"
